version: "3.7" 
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80
    links:
      - mysql-server

      
  mysql-server:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./data/:/data/
    ports:
      - 3310:3306


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: "root"
      PMA_PASSWORD: "secret"
    ports:
      - 5010:80
    depends_on:
      - mysql-server
    links:
      - mysql-server